---
- name: Update the monitoring scripts
  hosts: dell,hp

  vars:
    cpu_script: "/home/pranshu/scripts/cpu_util"
    memory_script: "/home/pranshu/scripts/mem_util"
    disk_script: "/home/pranshu/scripts/disk_util"

  tasks:
    - name: Upload the CPU usage script
      ansible.builtin.copy:
        src: cpu_util.txt
        dest: {{ cpu_script }}
        mode: 0700

    - name: Upload the Memory usage script
      ansible.builtin.copy:
        src: mem_util.txt
        dest: {{ memory_script }}
        mode: 0700

    - name: Upload the Disk usage script
      ansible.builtin.copy:
        src: disk_util.txt
        dest: {{ disk_script }}
        mode: 0700

    - name: Check CPU Usage Every 15 Minutes
      ansible.builtin.cron:
        name: "check CPU usage"
        minute: "15"
        job: {{ cpu_script }}

    - name: Check Memory Usage Every 15 Minutes
      ansible.builtin.cron:
        name: "check Memory usage"
        minute: "15"
        job: {{ memory_script }}

    - name: Check Disk Usage Every 15 Minutes
      ansible.builtin.cron:
        name: "check Disk usage"
        minute: "15"
        job: {{ disk_script }}